version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: trainer-workload-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=trainer_workload

volumes:
  mongodb_data: